name: Rqalpha test
on: [push, pull_request]

jobs:
  run-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
    steps:
    - name: Install dependencies
      run: |
        # Install TA-Lib
          # wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          whoami
          ls -al
    - name: run test
      run:
        ls -al $HOME/.rqalpha/
        ls -al $HOME/.rqalpha/bundle/
        rqalpha download-bundle
        coverage run --source=rqalpha test.py
    - name: Cache bundle
      uses: actions/cache@v2
      with:
        path: |
          $HOME/.cache/pip
          $HOME/.rqalpha/bundle
